name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        path: '.'

    - name: Install dependencies
      run: npm install
      working-directory: ./server

    - name: Build TypeScript
      run: npm run build
      working-directory: ./server
      
    - name: Print dist directory
      run: ls -R ./dist
